Publish and dep updates (#1304)

diff --git a/.ado/release.yml b/.ado/release.yml
--- a/.ado/release.yml
+++ b/.ado/release.yml
@@ -1,24 +1,19 @@
-# The release pipeline to publish NPM packages to npmjs.com via ESRP ("beachball - release")
-# Based on https://github.com/microsoft/node-api-dotnet/blob/main/.ado/release.yml
+# This pipeline has stages to build artifacts and commit to git, then publish packages via ESRP.
+# Based on https://github.com/microsoft/node-api-dotnet/blob/main/.ado/publish.yml
+# see also https://github.com/microsoft/fluentui/blob/master/azure-pipelines.release.yml
+# references:
+# https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/overview
+# https://eng.ms/docs/coreai/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/migration/office-specific-guidance
 
 # Name of the run
 # NOTE: this is referenced in packages/beachball/src/env.ts as BUILD_BUILDNUMBER for some tests
 name: beachball-release-$(Date:yyyy-MM-dd).$(Rev:rr)
 
+# This script must never be triggered from YAML settings for security reasons.
+pr: none
 trigger: none
 
 resources:
-  pipelines:
-    # must match publishPipelineAlias variable
-    - pipeline: prepublish
-      project: ISS
-      source: beachball - prepublish
-      # trigger:
-      #   branches:
-      #     include:
-      #       - main
-      #       - user/elcraig/1es-pt-migration-publish
-
   repositories:
     - repository: OfficePipelineTemplates
       type: git
@@ -27,7 +22,7 @@ resources:
 
 variables:
   nodeVersion: 24
-  publishPipelineAlias: prepublish
+  tags: production
   packagesArtifactName: packed-packages
   releaseApiToolArtifactName: release-api-tool
 
@@ -36,27 +31,128 @@ extends:
   parameters:
     pool:
       name: Azure-Pipelines-1ESPT-ExDShared
-      vmImage: windows-latest
-      os: windows
+      image: windows-latest
+      os: windows # We need windows because compliance task only run on windows.
+    sdl:
+      codeql:
+        runSourceLanguagesInSourceAnalysis: true
 
     stages:
-      - stage: main_release
-        displayName: Publish packages
+      - stage: build
+        displayName: Build artifacts
         jobs:
-          - job: npm_release
+          - job: build
+            displayName: Build, test, pack
+
+            pool:
+              name: Azure-Pipelines-1ESPT-ExDShared
+              image: ubuntu-latest
+              os: linux
+
+            workspace:
+              clean: all
+
+            variables:
+              artifactPath: $(Build.StagingDirectory)/out
+              packagesArtifactPath: ${{ variables.artifactPath }}/packed-packages
+              releaseApiToolPath: ${{ variables.artifactPath }}/release-api-tool
+
+            templateContext:
+              outputParentDirectory: ${{ variables.artifactPath }}
+              outputs:
+                - output: pipelineArtifact
+                  artifactName: ${{ variables.packagesArtifactName }}
+                  path: ${{ variables.packagesArtifactPath }}
+                - output: pipelineArtifact
+                  artifactName: ${{ variables.releaseApiToolArtifactName }}
+                  path: ${{ variables.releaseApiToolPath }}
+
+            steps:
+              - checkout: self
+
+              - task: UseNode@1
+                displayName: Install Node.js ${{ variables.nodeVersion }}
+                retryCountOnTaskFailure: 1
+                inputs:
+                  version: ${{ variables.nodeVersion }}.x
+                  checkLatest: false
+
+              # For multiline scripts, we want the whole task to fail if any line of the script fails.
+              # ADO doesn't have bash configured this way by default. To fix we override the SHELLOPTS built-in variable.
+              # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
+              # The options below include ADO defaults (braceexpand:hashall:interactive-comments) plus
+              # errexit:errtrace for better error behavior.
+              - script: |
+                  echo "##vso[task.setvariable variable=shellopts]braceexpand:hashall:interactive-comments:errexit:errtrace"
+                displayName: Force exit on error (bash)
+
+              - script: |
+                  echo "node: `node -v`"
+                  echo "yarn: `yarn -v`"
+                  echo "npm: `npm -v`"
+                  printenv | sort
+                  git --no-pager config list
+                displayName: Show environment
+
+              - script: node scripts/preparePublishRegistry.ts
+                displayName: Prepare npm registry settings
+
+              - task: npmAuthenticate@0
+                displayName: npm authenticate
+                inputs:
+                  workingFile: $(Build.SourcesDirectory)/.npmrc
+
+              # This isn't used, it's just a clear way to check that auth is working
+              # (yarn install's auth errors can be very unclear)
+              - script: yarn npm info beachball
+                displayName: Get package to verify yarn auth
+
+              - script: yarn --immutable
+                displayName: Install dependencies
+
+              - script: yarn build --verbose
+                displayName: Build
+
+              - script: yarn test --verbose
+                displayName: Test
+
+              - task: AzureCLI@2
+                displayName: Get token and publish packages
+                inputs:
+                  azureSubscription: ogx-oss-release-bot
+                  scriptType: bash
+                  scriptLocation: scriptPath
+                  scriptPath: scripts/publish-with-github-app-token.sh
+
+              - script: |
+                  mkdir -p ${{ variables.releaseApiToolPath }}
+                  cp -r packages/esrp-npm-release/dist/index.js ${{ variables.releaseApiToolPath }}
+                displayName: Copy release API tool to staging directory
+
+              - script: ls -R '${{ variables.artifactPath }}'
+                displayName: Show all output files
+
+      - stage: publish
+        displayName: Publish packages
+        dependsOn: build
+        jobs:
+          - job: npm_publish
             displayName: NPM to npmjs.com
+
+            variables:
+              packagesArtifactPath: $(Agent.BuildDirectory)\${{ variables.packagesArtifactName }}
+              releaseApiToolPath: $(Agent.BuildDirectory)\${{ variables.releaseApiToolArtifactName }}
+
             templateContext:
               type: releaseJob
               isProduction: true
               inputs:
                 - input: pipelineArtifact
-                  pipeline: ${{ variables.publishPipelineAlias }}
                   artifactName: ${{ variables.packagesArtifactName }}
-                  targetPath: $(Agent.BuildDirectory)\${{ variables.packagesArtifactName }}
+                  targetPath: ${{ variables.packagesArtifactPath }}
                 - input: pipelineArtifact
-                  pipeline: ${{ variables.publishPipelineAlias }}
                   artifactName: ${{ variables.releaseApiToolArtifactName }}
-                  targetPath: $(Agent.BuildDirectory)\${{ variables.releaseApiToolArtifactName }}
+                  targetPath: ${{ variables.releaseApiToolPath }}
 
             # Use ESRP Release to securely publish to npmjs.com.
             steps:
@@ -67,8 +163,8 @@ extends:
                   version: ${{ variables.nodeVersion }}.x
                   checkLatest: false
 
-              - script: dir /S $(Agent.BuildDirectory)\${{ variables.packagesArtifactName }}
-                displayName: Show directory contents
+              - script: dir /S ${{ variables.packagesArtifactPath }}
+                displayName: Show packages artifact contents
 
               # Get credentials that will be used to temporarily upload zips to ogxesrptempstorage
               # in the OGX azure subscription
@@ -96,11 +192,11 @@ extends:
                   # "authcertname" and "signcertname" from EsrpRelease task
                   SecretsFilter: OGX-JSHost-Auth4,OGX-JSHost-Sign3
 
-              - script: node $(Agent.BuildDirectory)\${{ variables.releaseApiToolArtifactName }}\index.js
+              - script: node ${{ variables.releaseApiToolPath }}\index.js
                 displayName: Publish to npmjs.com using ESRP Release API wrapper
                 retryCountOnTaskFailure: 3
                 env:
-                  PACKED_PACKAGES_PATH: $(Agent.BuildDirectory)\${{ variables.packagesArtifactName }}
+                  PACKED_PACKAGES_PATH: ${{ variables.packagesArtifactPath }}
                   ESRP_PRODUCT_NAME: beachball
                   ESRP_NPM_TAG: test
                   ESRP_USER: elcraig@microsoft.com
